default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: webcam_rails_development

test:
  <<: *default
  database: webcam_rails_test

production:
  <<: *default
  database: webcam_rails_production
  username: webcam_rails
  password: <%= ENV['WEBCAM_RAILS_DATABASE_PASSWORD'] %>
